### ISSUE TITLE
[Suggestion] Character move list .txt file included in the game's directory by default

### ISSUE THREAD

**Issue by ghost** [alokforever/mh-reinstated#13]
I saw a thread on the tapatalk forums where the character moves list was provided for the new characters.

I'd request adding a txt file that includes this information packed together with the game installation itself, so incase I want to look up the more unusual key combos for some the new characters on how to do their moves, so I don't need to go to the internet to find this information.

It would be really helpful and allow me to enjoy the new characters more (and the old characters too, incase they have new moves or abilities).

**Comment by zeto0128** [comment]
Nice idea! Originally I was planning to add the moves list inside the game menu but I don't have much time yet. For the meantime, I'll be adding the move lists to a file.

**Comment by ghost** [comment]
Thank you, this is much appreciated!

To save time and keep things simple, the common controls that are universal for all characters (the ones that can be figured out by trying them out once or twice) can be simply mentioned at the beginning without needing to go into detail.

> **Universal for all playable characters**
> _Common character combat controls:
> Attack
> Attack + Up
> Attack + Down
> Attack (in air)
> Special
> Special + Up
> Special + Down
> Block + Special
> Block
> Throw
> 
> *Try these on all characters to see what they do, then refer to the character specific special abilities 
>
> section for advanced techniques.
> 
> Character specific advanced techniques:
> 
> **Wolverine**...
> Attack + Block = Taunt
> **Juggernaut**...
> etc etc_
