### ISSUE TITLE
[Question] What about Thor?

### ISSUE THREAD

**Issue by ghost** [alokforever/mh-reinstated#14]
Theres a version of Multihero that includes characters like Thor (and Sonya). I though the Thor character was really cool and fun to play with. I enjoyed him a lot. Can it be included in the zeto branch of the game too?

**Comment by zeto0128** [comment]
A long time ago after I finished Thor, my laptop became broken and we didn't have github yet. Nor a backup of the source code. I was planning to re-add him but not sure which characters should I prioriize first. Maybe after I add Deadpool or so I'll b adding Thor next.

**Comment by ghost** [comment]
Oh man, my condolences. I'm currently having both version of multihero installed, one with Thor and the fresh new Zeto branch that I'm still trying with all its new characters and cool features. I play both because Thor is so hilariously manly, powerful and loud. He rules! : D

Is there any way to decompile the existing Thor version to retrieve some of the code/graphics from it? It would make recovery far easier than starting from scratch. I got my copy of the Thor version from here:
https://www.mediafire.com/file/bqhp5o8eux1g5ux/MultiHero097%28Thor%29.zip

**Comment by zeto0128** [comment]
I doubt there is a way to retrieve the code, but fortunately the graphics are still there and can be taken from the graphics folder. I notice now that most people (even my friends) find Thor fascinating to play. If you want I can just add him to the next roster of characters (and with improved moves, of course).

**Comment by zeto0128** [comment]
By the way, Wonderwoman has a similar playstyle with Thor. After I finish with her flight mode, her moves will somewhat be resembling Thor in a way.

**Comment by ghost** [comment]
Yes I look forward to trying all the new characters that are included in the new Zeto branch, Wonderwoman included. I'm very excited for all the new content!

The thing about Thor that I really love are the sound effects, art and his moveset. His voice lines in particular sound so loud, booming and manly. Accompanied with the loud impact sounds when he does a ground pound, or hits other characters with the Mjolnir feels so satisfying. I love it all.

I also love the skydive ability (Special + in air) where he flies accross the stage like a comet. Also the Super Specials are super cool too. The Block + Down + Special is really fun when it succeeds, having Thor grab a single opponent, headbash them into a pulp, then spin the opponent around really fast, sending them flying into outer space at Mach 5. Thor is soo good to play as! : )

He was also fairly bug free, the only issues is that his Lightning Beam super special caused a lot of lag / slowdown temporarily and using the Mjolnir throw attack during the Train stage where the bridge occasionally sweeps by can have him become permanently stuck off screen if the bridge catched Thor while the Mjolnir is flying through the air. Other than, he's golden.

Shame about there not being an easy way to get his code back. If you ever get the chance to bring him back, then please do so! He's certainly worth the effort! : )

**Comment by zeto0128** [comment]
I don't why I didn't realize it but it's really a golden addition to the roster. Makes me remember the inspiration while making that character, since I'm a Marvel fan. It feels like reading the comics and watching the movie at the same time. 

It's decided. I'll be adding him next right after I finish what I'm currently doing which is the second Super Special of Wonderwoman.
